-- 1. Tạo bảng users (Lưu thông tin khách hàng)
CREATE TABLE IF NOT EXISTS users (
    user_id TEXT PRIMARY KEY,       -- ID của người dùng trên Discord
    name TEXT,                      -- Tên hiển thị
    unread_count INTEGER DEFAULT 0, -- Số tin nhắn chưa đọc
    avatar_path TEXT                -- Đường dẫn lưu ảnh đại diện dưới máy tính
);

-- 2. Tạo bảng messages (Lưu lịch sử tin nhắn)
CREATE TABLE IF NOT EXISTS messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- ID nội bộ tự tăng để sắp xếp thứ tự tin nhắn
    user_id TEXT REFERENCES users(user_id) ON DELETE CASCADE, -- Liên kết với bảng users
    sender_name TEXT,               -- Tên người gửi (Tên khách hoặc "Bot")
    text TEXT,                      -- Nội dung tin nhắn
    time TEXT,                      -- Thời gian gửi (VD: 01/04/2026 14:00)
    is_self BOOLEAN,                -- True nếu là Bot gửi, False nếu là khách gửi
    msg_id TEXT UNIQUE,             -- ID của tin nhắn trên Discord (Dùng để thu hồi/xóa)
    image_path TEXT,                -- Đường dẫn lưu ảnh đính kèm (nếu có)
    status TEXT DEFAULT 'Đã đọc'    -- Trạng thái tin nhắn (Đã đọc, Đã nhận, Đã gửi)
);